In [1]:
import pandas as pd

In [21]:
df = r'Brunei_Champion_GT5_tst_pred_w1d_m4hr_svm_nu0.01_krnrbf_gam0.01_01Aug2018_01Jul2019.csv'
dateparse = lambda x: pd.datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
dfoutput = pd.read_csv(df, parse_dates = ['timestamp'], date_parser = dateparse)
dfoutput.set_index(['timestamp'], inplace = True)
dfoutput['date'] = dfoutput.index

In [22]:
dfoutput.prediction = dfoutput.prediction.replace(1, 0)
dfoutput.prediction = dfoutput.prediction.replace(-1, 1)

dfoutput['Anomalies'] = 0
dfoutput.loc[(dfoutput['system_status'] == 'online') & (dfoutput['prediction'] == 1), 'Anomalies'] = 1

dfoutput['Alerts'] = 0
dfoutput.loc[(dfoutput['system_status'] == 'online') & (dfoutput['alert'] == 1) & (dfoutput['prediction'] == 1), 'Alerts'] = 1

In [23]:
df1 = dfoutput[['Anomalies','Alerts']].resample('W').sum()

In [24]:
df1

            Anomalies  Alerts
timestamp
2018-08-05          1       1
2018-08-12         72       5
2018-08-19        171      11
2018-08-26          5       4
2018-09-02        216       2
2018-09-09        141       2
2018-09-16          0       0
2018-09-23          0       0
2018-09-30        142       0
2018-10-07        403       0
2018-10-14         76       1
2018-10-21         48      29
2018-10-28          0       0
2018-11-04          0       0
2018-11-11          0       0
2018-11-18         75       0
2018-11-25         87       4
2018-12-02        128      11
2018-12-09         90       4
2018-12-16          4       2
2018-12-23        156      13
2018-12-30         18       7
2019-01-06        150       0
2019-01-13          0       0
2019-01-20          0       0
2019-01-27          0       0
2019-02-03          6       4
2019-02-10        140       0
2019-02-17          1       1
2019-02-24          0       0
2019-03-03          2       1
2019-03-10          0       0
2019-03-17          8       2
2019-03-24          3       1
2019-03-31        142       4
2019-04-07          0       0
2019-04-14          0       0
2019-04-21          0       0
2019-04-28          0       0
2019-05-05          0       0
2019-05-12          0       0
2019-05-19          0       0
2019-05-26        190       0
2019-06-02        845       4
2019-06-09        932      22
2019-06-16        898      21
2019-06-23        989      10
2019-06-30        949      11
2019-07-07          1       0